// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUBMbrnjHRCrBmXjzpI7q7ofV2SYk_sFE',
    appId: '1:85216397850:web:f09261e9423063d87c5fa3',
    messagingSenderId: '85216397850',
    projectId: 'moviles-17147',
    authDomain: 'moviles-17147.firebaseapp.com',
    storageBucket: 'moviles-17147.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAArMlm1rXAAMDavKWrzWJx_Pg0BVlxe0U',
    appId: '1:85216397850:android:bea86db87accddf77c5fa3',
    messagingSenderId: '85216397850',
    projectId: 'moviles-17147',
    storageBucket: 'moviles-17147.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR1Y_Ey0nIfJRt0NXstDfGNP0XIBtxYnk',
    appId: '1:85216397850:ios:58eef3d5f46dcbf57c5fa3',
    messagingSenderId: '85216397850',
    projectId: 'moviles-17147',
    storageBucket: 'moviles-17147.appspot.com',
    iosClientId: '85216397850-njs8npevbua7ssmhd2tlb5ipjp7dao1v.apps.googleusercontent.com',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR1Y_Ey0nIfJRt0NXstDfGNP0XIBtxYnk',
    appId: '1:85216397850:ios:58eef3d5f46dcbf57c5fa3',
    messagingSenderId: '85216397850',
    projectId: 'moviles-17147',
    storageBucket: 'moviles-17147.appspot.com',
    iosClientId: '85216397850-njs8npevbua7ssmhd2tlb5ipjp7dao1v.apps.googleusercontent.com',
    iosBundleId: 'com.example.app1',
  );
}
